create table eventman.REVINFO (REV integer not null, REVTSTMP bigint, primary key (REV));
alter table if exists eventman.roles alter column id set data type bigint;
alter table if exists eventman.roles alter column name set data type varchar(255);
create table eventman.roles_AUD (id bigint not null, REV integer not null, REVTYPE smallint, name varchar(255), primary key (REV, id));
create table eventman.roles_users (UserRole_id bigint not null, users_id bigint not null);
create table eventman.roles_users_AUD (REV integer not null, UserRole_id bigint not null, users_id bigint not null, REVTYPE smallint, primary key (REV, UserRole_id, users_id));
alter table if exists eventman.users alter column id set data type bigint;
alter table if exists eventman.users alter column email set data type varchar(255);
alter table if exists eventman.users alter column first_name set data type varchar(255);
alter table if exists eventman.users alter column last_name set data type varchar(255);
alter table if exists eventman.users add column organization varchar(255);
alter table if exists eventman.users alter column user_role set data type bigint;
create table eventman.users_AUD (id bigint not null, REV integer not null, REVTYPE smallint, email varchar(255), first_name varchar(255), last_name varchar(255), organization varchar(255), password varchar(255), user_role bigint, primary key (REV, id));
alter table if exists eventman.roles_users drop constraint if exists UKsnx09g5kxfrdi207cl1jhjmev;
alter table if exists eventman.roles_users add constraint UKsnx09g5kxfrdi207cl1jhjmev unique (users_id);
create sequence eventman.REVINFO_SEQ start with 1 increment by 50;
create sequence eventman.roles_SEQ start with 1 increment by 50;
alter table if exists eventman.roles_AUD add constraint FK3udarg0q4wa62rnnfcf6b46a2 foreign key (REV) references eventman.REVINFO;
alter table if exists eventman.roles_users add constraint FK4glr8k8swy5nti6n5x35ofucj foreign key (users_id) references eventman.users;
alter table if exists eventman.roles_users add constraint FKkhkt7drdva82us8oyjsaopdfc foreign key (UserRole_id) references eventman.roles;
alter table if exists eventman.roles_users_AUD add constraint FKnm7cspkdpg7a0yfigicq185qe foreign key (REV) references eventman.REVINFO;
alter table if exists eventman.users_AUD add constraint FKinrdywgyurfk2ojrfkard4ejn foreign key (REV) references eventman.REVINFO;